"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Droplets } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { EmptyState, PageHeader, ProgressBar } from "@/components/page";
import { api, today } from "@/lib/api";

type Entry = { id: number; amount_ml: number; logged_at: string };
function Hydration() { const date = today(); const client = useQueryClient(); const profile = useQuery({ queryKey: ["profile"], queryFn: () => api<{hydration_goal_ml: number}>("/profile") }); const logs = useQuery({ queryKey: ["hydration", date], queryFn: () => api<Entry[]>(`/hydration?local_date=${date}`) }); const add = useMutation({ mutationFn: (amount_ml: number) => api("/hydration", { method: "POST", body: JSON.stringify({ amount_ml, local_date: date }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["hydration"] }); client.invalidateQueries({ queryKey: ["summary"] }); toast.success("Water intake added"); }, onError: (e: Error) => toast.error(e.message) }); const total = logs.data?.reduce((sum, entry) => sum + entry.amount_ml, 0) ?? 0; const goal = profile.data?.hydration_goal_ml ?? 2500; return <main className="content"><PageHeader eyebrow="Daily hydration" title="Drink log" description="Set a goal that suits you in Settings; FitTrack doesn’t prescribe a universal amount."/><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="card p-6"><Droplets className="text-blue-600"/><p className="mt-3 text-4xl font-bold">{total} <span className="text-base font-medium text-slate-500">ml</span></p><p className="mt-1 text-sm text-slate-500">of your {goal} ml goal</p><div className="mt-4"><ProgressBar value={total} max={goal} color="bg-blue-600"/></div><div className="mt-6 grid grid-cols-3 gap-2">{[250,350,500].map((amount) => <button key={amount} className="btn btn-soft" onClick={() => add.mutate(amount)}>+{amount} ml</button>)}</div></section><section className="card p-5"><h2 className="font-semibold">Today’s entries</h2><div className="mt-3 space-y-2">{logs.data?.length ? logs.data.map((entry) => <div key={entry.id} className="flex justify-between rounded-lg bg-slate-50 p-3"><span>{new Date(entry.logged_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span><span className="font-semibold">{entry.amount_ml} ml</span></div>) : <EmptyState title="Nothing logged yet" detail="Use a quick-add button when you have a drink."/>}</div></section></div></main>; }
export default function HydrationPage() { return <AppShell><Hydration/></AppShell>; }
