"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Sparkles } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { EmptyState, PageHeader } from "@/components/page";
import { api } from "@/lib/api";
type Supplement={id:number;name:string;brand:string|null;category:string;stock_units:number|null;expiry_date:string|null};
const supplementOptions = ["Whey protein", "Creatine monohydrate", "Electrolytes", "Multivitamin", "Vitamin D", "Omega-3", "Custom supplement"];
function Supplements(){const client=useQueryClient();const [choice,setChoice]=useState(supplementOptions[0]);const [customName,setCustomName]=useState("");const [category,setCategory]=useState("protein powder");const items=useQuery({queryKey:["supplements"],queryFn:()=>api<Supplement[]>("/supplements")});const name=choice==="Custom supplement"?customName:choice;const add=useMutation({mutationFn:()=>api("/supplements",{method:"POST",body:JSON.stringify({name,category})}),onSuccess:()=>{setCustomName("");toast.success("Supplement added");client.invalidateQueries({queryKey:["supplements"]});},onError:(e:Error)=>toast.error(e.message)});return <main className="content"><PageHeader eyebrow="Your inventory" title="Supplements" description="Track items and your own schedule. FitTrack does not recommend supplements or prescribe doses."/><section className="card max-w-2xl p-5"><form className="grid gap-2 sm:grid-cols-[1fr_12rem_auto]" onSubmit={(e)=>{e.preventDefault();add.mutate();}}><div><label className="mb-1 block text-xs font-medium text-slate-600">Supplement</label><select className="input" value={choice} onChange={(e)=>setChoice(e.target.value)}>{supplementOptions.map((option)=><option key={option}>{option}</option>)}</select>{choice==="Custom supplement"&&<input className="input mt-2" required placeholder="Supplement name" value={customName} onChange={(e)=>setCustomName(e.target.value)}/>}</div><div><label className="mb-1 block text-xs font-medium text-slate-600">Category</label><select className="input" value={category} onChange={(e)=>setCategory(e.target.value)}><option>protein powder</option><option>creatine</option><option>electrolytes</option><option>multivitamin</option><option>other</option></select></div><button className="btn btn-primary self-end" disabled={!name.trim()}>Add</button></form></section><section className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.data?.length?items.data.map((item)=><article className="card p-5" key={item.id}><Sparkles size={18} className="text-amber-600"/><p className="mt-3 font-semibold">{item.name}</p><p className="mt-1 text-sm capitalize text-slate-500">{item.category}</p>{item.stock_units!==null&&<p className="mt-4 text-xs text-slate-500">Stock: {item.stock_units} units</p>}</article>):<div className="md:col-span-2 xl:col-span-3"><EmptyState title="No supplements in inventory" detail="Choose an item you personally use, or add your own."/></div>}</section></main>}
export default function SupplementsPage(){return <AppShell><Supplements/></AppShell>}
