"use client";
import { useQuery } from "@tanstack/react-query";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/app-shell";
import { EmptyState, PageHeader } from "@/components/page";
import { api } from "@/lib/api";
type Nutrition={date:string;calories:number;protein_g:number}; type Activity={date:string;steps:number;distance_km:number};
function Analytics(){const nutrition=useQuery({queryKey:["analytics-nutrition"],queryFn:()=>api<Nutrition[]>("/analytics/nutrition?days=14")});const activity=useQuery({queryKey:["analytics-activity"],queryFn:()=>api<Activity[]>("/analytics/activity?days=14")});const chart=<T extends object,>({data,dataKey,color}:{data:T[];dataKey:keyof T;color:string})=>data.length?<div className="h-64"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={(v)=>String(v).slice(5)} fontSize={12}/><YAxis fontSize={12}/><Tooltip/><Line type="monotone" dataKey={String(dataKey)} stroke={color} strokeWidth={3} dot={{r:3}}/></LineChart></ResponsiveContainer></div>:<EmptyState title="Not enough data yet" detail="Log entries over a few days to make this trend useful."/>;return <main className="content"><PageHeader eyebrow="Measured trends" title="Analytics" description="Charts distinguish your logged information from estimates. Interpret trends over time, not isolated data points."/><div className="grid gap-5 xl:grid-cols-2"><section className="card p-5"><h2 className="font-semibold">Calories over 14 days</h2><p className="mb-4 text-sm text-slate-500">Food diary entries</p>{chart({data:nutrition.data??[],dataKey:"calories",color:"#0f766e"})}</section><section className="card p-5"><h2 className="font-semibold">Steps over 14 days</h2><p className="mb-4 text-sm text-slate-500">Manual activity entries</p>{chart({data:activity.data??[],dataKey:"steps",color:"#0284c7"})}</section></div></main>}
export default function AnalyticsPage(){return <AppShell><Analytics/></AppShell>}
