"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { BellRing } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { EmptyState, PageHeader } from "@/components/page";
import { api } from "@/lib/api";
type Reminder={id:number;title:string;reminder_type:string;scheduled_time:string;recurrence:string;enabled:boolean};
function Schedule(){const client=useQueryClient();const [title,setTitle]=useState("");const [time,setTime]=useState("08:00");const reminders=useQuery({queryKey:["schedule"],queryFn:()=>api<Reminder[]>("/schedule")});const add=useMutation({mutationFn:()=>api("/schedule",{method:"POST",body:JSON.stringify({title,scheduled_time:`${time}:00`,reminder_type:"custom",recurrence:"daily",enabled:true})}),onSuccess:()=>{setTitle("");toast.success("Reminder schedule saved");client.invalidateQueries({queryKey:["schedule"]});},onError:(e:Error)=>toast.error(e.message)});return <main className="content"><PageHeader eyebrow="Unified schedule" title="Routines and reminders" description="Planned events remain separate from completed logs. Delivery is not guaranteed when a browser or device is unavailable."/><div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><section className="card h-fit p-5"><h2 className="font-semibold">New reminder</h2><form className="mt-4 space-y-3" onSubmit={(e)=>{e.preventDefault();add.mutate();}}><input className="input" required value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="e.g. Afternoon walk"/><input className="input" type="time" value={time} onChange={(e)=>setTime(e.target.value)}/><button className="btn btn-primary w-full">Add daily reminder</button></form></section><section className="space-y-3">{reminders.data?.length?reminders.data.map((item)=><article className="card flex items-center gap-3 p-5" key={item.id}><span className="rounded-xl bg-teal-50 p-2 text-teal-700"><BellRing size={18}/></span><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm capitalize text-slate-500">{item.scheduled_time.slice(0,5)} · {item.recurrence}</p></div></article>):<EmptyState title="No reminders scheduled" detail="Create a routine reminder you want FitTrack to surface."/>}</section></div></main>}
export default function SchedulePage(){return <AppShell><Schedule/></AppShell>}
