"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { LockKeyhole, Pill } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { EmptyState, PageHeader } from "@/components/page";
import { api, today } from "@/lib/api";
type Medication={id:number;name:string;medication_type:string|null;dosage_text:string;schedule_times:string[];start_date:string;end_date:string|null};
function Medications(){const client=useQueryClient();const [name,setName]=useState("");const [dosage,setDosage]=useState("");const [time,setTime]=useState("09:00");const items=useQuery({queryKey:["medications"],queryFn:()=>api<Medication[]>("/medications")});const add=useMutation({mutationFn:()=>api("/medications",{method:"POST",body:JSON.stringify({name,dosage_text:dosage,schedule_times:[time],start_date:today()})}),onSuccess:()=>{setName("");setDosage("");toast.success("Medication record saved");client.invalidateQueries({queryKey:["medications"]});},onError:(e:Error)=>toast.error(e.message)});return <main className="content"><PageHeader eyebrow="Sensitive information" title="Medication tracker" description="Keep your prescribed information organized. FitTrack never changes schedules, suggests replacement doses, or advises on missed doses."/><div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><section className="card h-fit p-5"><div className="mb-4 flex gap-2 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900"><LockKeyhole size={16} className="mt-0.5 shrink-0"/>Avoid putting medication names into browser notification previews. Reminder delivery depends on permissions, connectivity, and device settings.</div><form className="space-y-3" onSubmit={(e)=>{e.preventDefault();add.mutate();}}><input className="input" required value={name} onChange={(e)=>setName(e.target.value)} placeholder="Medication name"/><input className="input" required value={dosage} onChange={(e)=>setDosage(e.target.value)} placeholder="Prescribed dosage text"/><label><span className="mb-1 block text-xs font-medium">Scheduled time</span><input className="input" type="time" value={time} onChange={(e)=>setTime(e.target.value)}/></label><button className="btn btn-primary w-full">Save private record</button></form></section><section className="space-y-3">{items.data?.length?items.data.map((item)=><article className="card p-5" key={item.id}><div className="flex items-center gap-2"><Pill size={18} className="text-rose-600"/><p className="font-semibold">{item.name}</p></div><p className="mt-2 text-sm text-slate-600">{item.dosage_text}</p><p className="mt-2 text-xs text-slate-500">Scheduled: {item.schedule_times.join(", ") || "No time entered"}</p></article>):<EmptyState title="No medication records" detail="Add a prescribed medication only if you want it tracked here."/>}</section></div></main>}
export default function MedicationsPage(){return <AppShell><Medications/></AppShell>}
