"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page";
import { api } from "@/lib/api";
type Profile={units:string;timezone:string;height_cm:number|null;calorie_goal:number;protein_goal_g:number;carb_goal_g:number;fat_goal_g:number;fiber_goal_g:number;step_goal:number;hydration_goal_ml:number};
function Settings(){const client=useQueryClient();const profile=useQuery({queryKey:["profile"],queryFn:()=>api<Profile>("/profile")});const [values,setValues]=useState<Profile|null>(null);useEffect(()=>{if(profile.data)setValues(profile.data)},[profile.data]);const save=useMutation({mutationFn:()=>api("/profile",{method:"PUT",body:JSON.stringify(values)}),onSuccess:()=>{toast.success("Preferences saved");client.invalidateQueries({queryKey:["profile"]});client.invalidateQueries({queryKey:["summary"]});},onError:(e:Error)=>toast.error(e.message)});if(!values)return <main className="content"><div className="h-48 animate-pulse rounded-xl bg-slate-200"/></main>;const fields=[['calorie_goal','Daily calories'],['protein_goal_g','Protein (g)'],['carb_goal_g','Carbohydrates (g)'],['fat_goal_g','Fat (g)'],['fiber_goal_g','Fiber (g)'],['step_goal','Daily steps'],['hydration_goal_ml','Hydration (ml)']] as const;return <main className="content"><PageHeader eyebrow="Preferences" title="Your targets, your settings" description="These values are used only for progress comparisons; they are not medical recommendations."/><section className="card max-w-3xl p-6"><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label])=><label key={key}><span className="mb-1 block text-sm font-medium">{label}</span><input className="input" type="number" min="0" value={values[key]} onChange={(e)=>setValues({...values,[key]:Number(e.target.value)})}/></label>)}<label><span className="mb-1 block text-sm font-medium">Units</span><select className="input" value={values.units} onChange={(e)=>setValues({...values,units:e.target.value})}><option value="metric">Metric</option><option value="imperial">Imperial</option></select></label><label><span className="mb-1 block text-sm font-medium">Time zone</span><input className="input" value={values.timezone} onChange={(e)=>setValues({...values,timezone:e.target.value})}/></label></div><button className="btn btn-primary mt-6" onClick={()=>save.mutate()} disabled={save.isPending}>Save settings</button></section></main>}
export default function SettingsPage(){return <AppShell><Settings/></AppShell>}
